### ISSUE TITLE
Cannot run tests from tarball at pypi

### ISSUE THREAD

**Issue by xnox** [fusionbox/django-pyscss#30]
From:
https://pypi.python.org/packages/source/d/django-pyscss/django-pyscss-1.0.6.tar.gz

I cannot run tests as it does not contain testproject nor tests

Could you please adjust things such that those end up in the pypi tarball, but NB! not installed as toplevel modules.

**Comment by rockymeza** [comment]
Hi @xnox,

Just curious, why do you want to run the tests from the tarball? I wasn't aware that people were usually doing that, but if it's common, we may want to change the rest of our open source project packaging as well.

Also, do you have examples of other projects that do this? For example, Django has some tests that live inside the packaged modules and some that live outside.

In addition, we have some CSS files that are required to run the tests, and I think that we would also have some images and stuff that are in the tests. The tests also write files to the disk (I think), I'm a little worried about what would happen if they were run from the packaged version.

Thoughts?

**Comment by xnox** [comment]
Heya,

On 23 February 2015 at 13:57, Rocky Meza <notifications@github.com> wrote:

> Hi @xnox <https://github.com/xnox>,
>
> Just curious, why do you want to run the tests from the tarball? I wasn't
> aware that people were usually doing that, but if it's common, we may want
> to change the rest of our open source project packaging as well.
>
> Also, do you have examples of other projects that do this? For example,
> Django has some tests that live inside the packaged modules and some that
> live outside.
>
> In addition, we have some CSS files that are required to run the tests,
> and I think that we would also have some images and stuff that are in the
> tests. The tests also write files to the disk (I think), I'm a little
> worried about what would happen if they were run from the packaged version.
>
> Thoughts?
>

I use pypi to package and install things from source tarballs uploaded
there. It has consistent api, and easy way to checksum validate downloads,
and has a hence of ownership of projects. On github - there can be loads of
forks everyone pretending to be the upstream, thus is not reliable to get
tarballs in general.

It's just a matter of tweaking MANIFEST.in or using include_package_data/
package_data/exclude_package_data to include test suites in the sdist, but
not install it in the eggs/binarydist.


-- 
Regards,

Dimitri.

**Comment by rockymeza** [comment]
Hi @xnox,

I finally got around to this. You can do it with the 2.0.0 version of the library.

Thanks and sorry it took so long
